language: python

python:
  - 3.7

services:
  - postgresql

env:
  - DJANGO=2.2.3

before_install:
  - export DJANGO_SETTINGS_MODULE=studenthub.config.settings
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE studenthub;" -U postgres

script:
  - python manage.py migrate
  - python manage.py test